# Generated by Django 3.2.6 on 2021-08-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('specialist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STATUS_PENDING', 'Pending'), ('STATUS_OK', 'Ok'), ('STATUS_EXHAUSTED', 'Exhausted')], default='STATUS_PENDING', max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialist.specialist')),
            ],
        ),
    ]
